### ISSUE TITLE
Raphael dependency not working

### ISSUE THREAD

**Issue by dmmz** [liuhong1happy/react-raphael#1]
After installing react-raphael, when trying to use it, it does not find the module 'raphael'. I guess this is because it is specified as a 'devDependency' in package.json. It should be specified simply as a dependency instead.  This means that in 'raphael-react' project,  'raphael' module should have been installed using 'npm install --save raphael' instead of '--save-dev'

**Comment by liuhong1happy** [comment]
Yes, you are right ! It is specified as a 'devDependency' in package.json.
Please install 'raphael' in 'raphael-react' project using npm install --save raphael,
or specifying the externals in webpack config file.
