### ISSUE TITLE
utils工具类使用raphael page.setSize参数有错误

### ISSUE THREAD

**Issue by penxian** [liuhong1happy/react-raphael#2]
在如下中
https://github.com/liuhong1happy/react-raphael/blob/master/lib/utils.js#L146

使用raphael 方法错误 `paper.setSize({ width: width, height: height });`

应该如此使用`Paper.setSize(width, height)` 不是传入对象

api url ：http://dmitrybaranovskiy.github.io/raphael/reference.html#Paper.setSize

**Comment by liuhong1happy** [comment]
@penxian 非常感谢，在0.8.2版本中问题已经修改。
