### ISSUE TITLE
React v15

### ISSUE THREAD

**Issue by CarolineBoyer** [liuhong1happy/react-raphael#4]
Thank you for this lib !

Using react v15.x, a warning comes up :
warning.js?8a56:36 Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

Here is a link for possible solution : https://facebook.github.io/react/warnings/dont-call-proptypes.html

Is your dependency on react v0.14 really necessary ? I could try to check this if you want ( though not really confident).

**Comment by liuhong1happy** [comment]
Now, the version `0.9.0` is using react v15.x.
