### ISSUE TITLE
Animation not working on sets?

### ISSUE THREAD

**Issue by rohn** [liuhong1happy/react-raphael#6]
I can't seem to get animation to work for sets...

a simplest example:

```
const growAnimation = Raphael.animation({ transform:'"S5"' }, 300);

<Set animate={growAnimation} >
  <Circle x={100} y={200} r={5} />
  <Circle x={200} y={200} r={15} />
</Set>
```

but if I put the `animate={growAnimation}` direction on each of the `<Circle>`s then they do animate immediately on component load.

**Comment by liuhong1happy** [comment]
please see http://dmitrybaranovskiy.github.io/raphael/reference.html#Element.transform
