### ISSUE TITLE
update npm package?

### ISSUE THREAD

**Issue by rohn** [liuhong1happy/react-raphael#8]
May I ask if you might update the npm package with latest version of this GitHub repo?

I apologize for creating an issue to ask if you planned to do this, but I don't have another way to contact you. 

I am very appreciative of this repo and am currently using it for a project 😄 Thank you for your awesome work and contributing to the open source community.

**Comment by liuhong1happy** [comment]
The new version(`0.9.0-rc`) had published(but only for test).
